<?php

namespace Proxies\__CG__\Foodsquare\CommonBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Users extends \Foodsquare\CommonBundle\Entity\Users implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'id', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'pin', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'nom', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'prenom', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'email', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'facebookId', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'token', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'username', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'role', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'locked', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'dateInscription', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'photo', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'password', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'salt', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'lockedAt');
        }

        return array('__isInitialized__', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'id', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'pin', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'nom', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'prenom', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'email', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'facebookId', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'token', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'username', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'role', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'locked', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'dateInscription', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'photo', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'password', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'salt', '' . "\0" . 'Foodsquare\\CommonBundle\\Entity\\Users' . "\0" . 'lockedAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Users $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookId($facebookId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookId', array($facebookId));

        return parent::setFacebookId($facebookId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookId', array());

        return parent::getFacebookId();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', array($token));

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', array());

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', array($role));

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', array());

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($locked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', array($locked));

        return parent::setLocked($locked);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocked', array());

        return parent::getLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateInscription($dateInscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateInscription', array($dateInscription));

        return parent::setDateInscription($dateInscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateInscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateInscription', array());

        return parent::getDateInscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', array($photo));

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', array());

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setLockedAt($lockedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLockedAt', array($lockedAt));

        return parent::setLockedAt($lockedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getLockedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLockedAt', array());

        return parent::getLockedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setRate(\Foodsquare\CommonBundle\Entity\RateThread $rate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRate', array($rate));

        return parent::setRate($rate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRate', array());

        return parent::getRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPin($pin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPin', array($pin));

        return parent::setPin($pin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPin', array());

        return parent::getPin();
    }

}
