<?php

namespace Foodsquare\CommonBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Doctrine\DBAL\Types\Type;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
    public function getNearbyRestaurant($latitude, $longitude, $distance)
    {

        $rsm = new ResultSetMappingBuilder($this->getEntityManager());
        $rsm->addRootEntityFromClassMetadata('Foodsquare\CommonBundle\Entity\Restaurant', 'r');
        $rsm->addScalarResult('distance', 'distance');

        $query = $this->_em->createNativeQuery(
          "SELECT r.*,
            ( 6371 * acos( cos( radians(?) ) * cos( radians( r.latitude ) ) * 
            cos( radians( r.longitude ) - radians(?) ) + sin( radians(?) ) * 
            sin( radians( r.latitude ) ) ) ) AS distance 
            FROM Restaurant r
            GROUP BY r.id HAVING distance < ? 
            ORDER BY distance", $rsm
        );   

        $query->setParameter(1, $latitude);
        $query->setParameter(2, $longitude);
        $query->setParameter(3, $latitude);
        $query->setParameter(4, $distance, Type::INTEGER);


        return $query->getResult();

    }
    
    public function searchRestaurant($name){
        
        $qb =  $this->createQueryBuilder('r');
        $qb     ->join('r.rate', 'ra')
                ->where($qb->expr()->like('r.nom', $qb->expr()->literal("%".$name."%")))
                ->orderBy('ra.average', 'DESC')
                ->addOrderBy('r.googleRate', 'DESC');
        
        try {
            return $qb->getQuery()
                  ->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
